# Generated by Django 4.2.13 on 2026-05-08 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_date', models.DateField()),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='completed', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='habits.habit')),
            ],
            options={
                'db_table': 'habit_entries',
                'ordering': ['-completed_date'],
                'indexes': [models.Index(fields=['habit', 'completed_date'], name='habit_entri_habit_i_81925e_idx'), models.Index(fields=['status'], name='habit_entri_status_993506_idx'), models.Index(fields=['completed_date'], name='habit_entri_complet_360692_idx')],
                'unique_together': {('habit', 'completed_date')},
            },
        ),
    ]
